// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SilverHub.Infrastructure.Persistence;

#nullable disable

namespace SilverHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SilverHubDbContext))]
    [Migration("20260703155940_AddHeroes")]
    partial class AddHeroes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SilverHub.Domain.Heroes.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Boudoir")
                        .HasColumnType("boolean")
                        .HasColumnName("boudoir");

                    b.Property<string>("BreakdownMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("breakdown_markdown");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("canonical_name");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("damage_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EquipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equip_type");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faction");

                    b.Property<int>("FriendshipMax")
                        .HasColumnType("integer")
                        .HasColumnName("friendship_max");

                    b.Property<bool>("HasResonantia")
                        .HasColumnType("boolean")
                        .HasColumnName("has_resonantia");

                    b.Property<bool>("Limited")
                        .HasColumnType("boolean")
                        .HasColumnName("limited");

                    b.Property<string>("MoonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moon_type");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("ResonantiaTraitsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resonantia_traits_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("heroes", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("VariantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("variant_name");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Kind", "SortOrder");

                    b.ToTable("hero_images", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroPreferredArtifact", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<string>("ArtifactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("artifact_name");

                    b.Property<string>("ArtifactSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("artifact_slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("HeroId", "ArtifactName");

                    b.HasIndex("HeroId", "SortOrder");

                    b.ToTable("hero_preferred_artifacts", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuffsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("buffs");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("DebuffsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("debuffs");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_md");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<string>("IconKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_type");

                    b.Property<string>("ValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Type", "SortOrder");

                    b.ToTable("hero_skills", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroTag", b =>
                {
                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag");

                    b.HasKey("HeroId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("hero_tags", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Synergies.Synergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description2Markdown")
                        .HasColumnType("text")
                        .HasColumnName("description2_md");

                    b.Property<string>("Description3Markdown")
                        .HasColumnType("text")
                        .HasColumnName("description3_md");

                    b.Property<string>("Icon2Key")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon2_key");

                    b.Property<string>("Icon3Key")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon3_key");

                    b.Property<string>("IconKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("synergies", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Synergies.SynergyMember", b =>
                {
                    b.Property<Guid>("SynergyId")
                        .HasColumnType("uuid")
                        .HasColumnName("synergy_id");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("SynergyId", "HeroId");

                    b.HasIndex("HeroId");

                    b.HasIndex("SynergyId", "Role", "SortOrder");

                    b.ToTable("synergy_members", (string)null);
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroImage", b =>
                {
                    b.HasOne("SilverHub.Domain.Heroes.Hero", "Hero")
                        .WithMany("Images")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroPreferredArtifact", b =>
                {
                    b.HasOne("SilverHub.Domain.Heroes.Hero", "Hero")
                        .WithMany("PreferredArtifacts")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroSkill", b =>
                {
                    b.HasOne("SilverHub.Domain.Heroes.Hero", "Hero")
                        .WithMany("Skills")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.HeroTag", b =>
                {
                    b.HasOne("SilverHub.Domain.Heroes.Hero", "Hero")
                        .WithMany("Tags")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("SilverHub.Domain.Synergies.SynergyMember", b =>
                {
                    b.HasOne("SilverHub.Domain.Heroes.Hero", "Hero")
                        .WithMany("SynergyMemberships")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilverHub.Domain.Synergies.Synergy", "Synergy")
                        .WithMany("Members")
                        .HasForeignKey("SynergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Synergy");
                });

            modelBuilder.Entity("SilverHub.Domain.Heroes.Hero", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PreferredArtifacts");

                    b.Navigation("Skills");

                    b.Navigation("SynergyMemberships");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SilverHub.Domain.Synergies.Synergy", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
